# Generated by Django 4.2.5 on 2023-09-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Discipline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(blank=True, default="", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(blank=True, default="", max_length=100)),
                ("bio", models.TextField(max_length=1000)),
                (
                    "facebook",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "instagram",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "website",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                ("picture", models.CharField(default="", max_length=100)),
                ("discipline", models.ManyToManyField(to="lessons.discipline")),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(blank=True, default="", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(blank=True, default="", max_length=100)),
                ("summary", models.TextField(max_length=1000)),
                ("duration", models.CharField(max_length=100)),
                ("release_date", models.DateTimeField()),
                ("image_link", models.CharField(max_length=100)),
                ("video_link", models.CharField(max_length=100)),
                ("intensity", models.IntegerField()),
                ("difficulty", models.IntegerField()),
                ("discipline", models.ManyToManyField(to="lessons.discipline")),
                ("instructor", models.ManyToManyField(to="lessons.instructor")),
                ("skill", models.ManyToManyField(to="lessons.skill")),
            ],
        ),
    ]
