# Generated by Django 4.2.5 on 2023-10-13 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Serie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100)),
                ("summary", models.TextField(max_length=1000)),
                ("image_link", models.CharField(max_length=100)),
                ("video_link", models.CharField(max_length=100)),
                ("intensity", models.IntegerField()),
                ("difficulty", models.IntegerField()),
                ("discipline", models.ManyToManyField(to="lessons.discipline")),
                ("instructor", models.ManyToManyField(to="lessons.instructor")),
                ("skill", models.ManyToManyField(to="lessons.skill")),
            ],
        ),
        migrations.AddField(
            model_name="lesson",
            name="serie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lessons.serie",
            ),
        ),
    ]
