# Generated by Django 4.2.5 on 2023-10-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0003_style_lesson_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="style",
            name="description",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="style",
            name="picture",
            field=models.CharField(default="", max_length=100),
        ),
    ]
